app2/urls.py
from django.urls import path
from app2.views import app2_specific
app_name='app2'
urlpatterns=[path('app2_specific/',app2_specific,name='app2_specific'),]

project7/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import hai,bye
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',hai,name='hai'),
    path('bye/',bye,name='bye'),
    path('app2/',include('app2.urls'),)
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

def bye(request):
    return render(request,'bye.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_specific(request):
    return render(request,'app2_specific.html')

templates/app2_specific.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to  app2_specific</h1>
        <h2><a href="{% url 'hai' %}">naviagate to hai</a></h2>
        <h2><a href="{% url 'bye' %}">Naviagate to Bye</a></h2>
    </center>
</body>
</html>

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Bye html page</h1>
        <h2><a href="{% url 'hai' %}">Navigate to HAI</a></h2>
        <h2><a href="{% url 'app2:app2_specific' %}">Naviagate to app2_specific</a></h2>
    </center>
</body>
</html>

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Hai html page</h1>
        <h2><a href="{% url 'bye' %}">Navigate to BYE</a></h2>
        <h2><a href="{% url 'app2:app2_specific' %}">Naviagate to app2_specific</a></h2>
    </center>
</body>
</html>